name: Quality Checks

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  php-analysis:
    uses: skuskusku13/workflows-reusable/.github/workflows/php-quality.yml@1.0.0
    with:
      php-version: '8.4'
      php-extensions: 'pdo, pdo_mysql'
